#pragma config(Sensor, in1,    Catapult,       sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task catapult_task() {
 resetSensor(Catapult);
	while (true) {
		if (vexRT[Btn5U]) {
			catapult(127);
			delay(450);
		}
		else if(SensorValue(Catapult) > 750) {
				catapult(90);
			}
			else if(SensorValue(Catapult) > 450){
				catapult(45);
			}
			else {
				catapult(15);
			}
		}

		delay(20);
	}
