#pragma config(Sensor, in1,    Catapult,       sensorPotentiometer)
#pragma config(Motor,  port1,           Left_Mid,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Left_Back,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Right_Mid,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Catapult_1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Catapult_2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Right_Back,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Descorer,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Right_Front,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Left_Front,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "motor.h"
#include "catapult.c"
task
main() {
	startTask(catapult_task);
	int l = 0;
	int r = 0;
	while (true) {
		r = abs(vexRT[Ch2])<15 ? 0 : vexRT[Ch2];
		l = abs(vexRT[Ch3])<15 ? 0 : vexRT[Ch3];

		tank(l, r);

		intake((vexRT[Btn6U]-vexRT[Btn6D])*127);

		descorer((vexRT[Btn8D]-vexRT[Btn8R])*127);

		delay(20);
	}
}
